kubewatch:
  acdNamespace: devtroncd
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m
  image:
    repo: quay.io/devtron/kubewatch
    tag: v0.1.3
  podLabels:
    component: kubewatch
