{{- if .Values.passboltEnv.plain.PASSBOLT_PLUGINS_JWT_AUTHENTICATION_ENABLED }}
{{- $type := "sec" -}}
{{- $action := "jwt" -}}
{{- $Name := include "passbolt-library.fullname" . -}}
{{- $fullName := printf "%s-%s-%s" $Name $type $action -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "passbolt-library.labels" . | nindent 4 }}
    {{- include "passbolt-library.selectorLabels" . | nindent 4 }}
    {{- include "passbolt-library.typelabels" (dict "action" $action "type" $type) | nindent 4 }}
type: Opaque
data:
  {{- if and ( .Values.jwtServerPrivate ) ( .Values.jwtServerPublic )}}
  jwt.key: {{ .Values.jwtServerPrivate }}
  jwt.pem: {{ .Values.jwtServerPublic }}
  {{- else -}}
  {{- $cert := genSelfSignedCertWithKey "" (list) (list) 3650 (genPrivateKey "rsa") }}
  jwt.key: {{ $cert.Key | b64enc }}
  jwt.pem: {{ $cert.Cert | b64enc  }}
{{- end }}
{{- end }}
