# Source: kubewatch/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: kubewatch
    chart: kubewatch-0.6.1
    heritage: "Tiller"
    release: "kubewatch"
  name: kubewatch-config
  namespace: {{ .Release.Namespace }}
data:
  .kubewatch.yaml: |
    handler:
      webhook:
        enabled: false
        url: http://devtroncd-event-handler-service-prod.devtroncd/event

    resource:
      daemonset: false
      deployment: false
      events: false
      job: false
      persistentvolume: false
      pod: false
      replicaset: false
      replicationcontroller: false
      services: false
---
# Source: kubewatch/templates/servieaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kubewatch
    chart: kubewatch-0.6.1
    heritage: Tiller
    release: kubewatch
  name: kubewatch
  namespace: {{ .Release.Namespace }}
---
# Source: kubewatch/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kubewatch
    chart: kubewatch-0.6.1
    heritage: Tiller
    release: kubewatch
  name: kubewatch
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
    - pods
    - namespaces
    - services
    - deployments
    - replicationcontrollers
    - replicasets
    - daemonsets
    - persistentvolumes
    - events
    - workflows
    verbs:
    - list
    - watch
    - get
  - apiGroups:
    - apps
    resources:
    - daemonsets
    - deployments
    - deployments/scale
    - replicasets
    - replicasets/scale
    - statefulsets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - extensions
    resources:
    - daemonsets
    - deployments
    - deployments/scale
    - replicasets
    - replicasets/scale
    - replicationcontrollers/scale
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - batch
    resources:
    - cronjobs
    - jobs
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - argoproj.io
    resources:
    - workflows
    - applications
    verbs:
    - get
    - list
    - watch
---
# Source: kubewatch/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kubewatch
    chart: kubewatch-0.6.2
    heritage: Tiller
    release: kubewatch
  name: kubewatch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubewatch
subjects:
  - kind: ServiceAccount
    name: kubewatch
    namespace: {{ .Release.Namespace }}
---
# Source: kubewatch/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubewatch
    chart: kubewatch-0.6.1
    heritage: "Tiller"
    release: "kubewatch"
{{ toYaml .Values.kubewatch.podLabels | indent 4 }}
  name: kubewatch
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubewatch
      release: kubewatch
  template:
    metadata:
      annotations:
        checksum/config-map: ae58540f4f666750bf92d3af7f94dbccd3bbea95fe76308c7572469c36d55bdc
      labels:
        app: kubewatch
        release: "kubewatch"
        chart: kubewatch-0.6.1
{{ toYaml .Values.kubewatch.podLabels | indent 8 }}
    spec:
      containers:
      - name: kubewatch
        image: {{ .Values.kubewatch.image.repo }}:{{ .Values.kubewatch.image.tag }}
        env:
        - name: DEFAULT_NAMESPACE
          value: "devtron-ci"
        - name: CI_INFORMER
          value: "true"
        - name: ACD_NAMESPACE
          value: {{ .Values.kubewatch.acdNamespace }}
        - name: ACD_INFORMER
          value: "true"
        imagePullPolicy: Always
        volumeMounts:
        - name: kubewatch-config-map
          mountPath: /root/.kubewatch.yaml
          subPath: .kubewatch.yaml
        resources:
{{ toYaml .Values.kubewatch.resources | indent 10 }}
      serviceAccountName: kubewatch
      tolerations: []
      restartPolicy: Always
      volumes:
      - name: kubewatch-config-map
        configMap:
          name: kubewatch-config
